version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.3.1
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0

jobs:
  filter:
    executor: path-filtering/default
    steps:
      - git-shallow-clone/checkout:
          depth: 1
      - path-filtering/set-parameters:
          base-revision: main
          mapping: |
            src/.* build-code true
      - continuation/continue:
          configuration_path: .circleci/continue.yml
          parameters: /tmp/pipeline-parameters.json

workflows:
  setup:
    jobs:
      - filter
